id: PDBFF22C4
initial_creation_type: ocr
source_metadata:
  volumes:
    190cd941322a444ea9e5d52fd8cdebf8:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: སེམས་བསྐྱེད་པ་དང་སྡོམ་པའི་ཆོ་གའི་རིམ་པ།
      total_pages: 1498
      volume_number: 65
